# Generated by Django 5.2.4 on 2025-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_alter_assembly_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='installing_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalassembly',
            name='installing_done',
            field=models.BooleanField(default=False),
        ),
    ]
