# Generated by Django 5.2.4 on 2025-08-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_assembly_installing_done_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'permissions': [('worker', 'Assembly worker')]},
        ),
    ]
