# Generated by Django 5.2.4 on 2025-09-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0006_alter_assembly_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'permissions': [('manager', 'Assembly manager')]},
        ),
    ]
