# Generated by Django 5.2.4 on 2025-11-25 16:49

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0007_alter_assembly_options'),
        ('order', '0017_alter_historicalorder_design_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено сборка'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='installing_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено установка'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='square',
            field=models.FloatField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сборшик'),
        ),
        migrations.AlterField(
            model_name='historicalassembly',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalassembly',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено сборка'),
        ),
        migrations.AlterField(
            model_name='historicalassembly',
            name='installing_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено установка'),
        ),
        migrations.AlterField(
            model_name='historicalassembly',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='historicalassembly',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='historicalassembly',
            name='square',
            field=models.FloatField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='historicalassembly',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сборшик'),
        ),
    ]
