# Generated by Django 5.2.4 on 2026-04-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0009_alter_assembly_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'permissions': [('manager', 'Assembly manager')], 'verbose_name': 'Сборка/Установка', 'verbose_name_plural': 'Сборки/Установки'},
        ),
        migrations.AlterModelOptions(
            name='historicalassembly',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Сборка/Установка', 'verbose_name_plural': 'historical Сборки/Установки'},
        ),
    ]
