version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "5000:80"
    depends_on:
      - back
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./media/:/media/
      - ./static/:/static/

  back:
    container_name: back
    image: khtkarimzhonov/api.ser-mebel.uz:latest
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    command: sh -c "uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --workers 4"
    volumes:
      - ./media/:/media/
      - ./static/:/static/
