# Generated by Django 5.2.4 on 2025-08-18 10:04

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_expense_cost_alter_expense_cost_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='income',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='income',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3),
        ),
    ]
