# Generated by Django 5.2.4 on 2025-08-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_expense_managers_alter_income_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('create_order_expose', 'Create expense in order instance')]},
        ),
    ]
