# Generated by Django 5.2.4 on 2025-08-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='income',
            managers=[
            ],
        ),
    ]
