# Generated by Django 5.2.4 on 2025-08-01 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField()),
                ('solution', models.IntegerField(choices=[(-1, 'Сотув амалга ошмади'), (0, 'Керак эмас'), (1, 'Қайта телефон қилиш'), (2, 'Телеграм орқали маълумот берилди'), (3, 'Мижоз келади, локация юборилди'), (4, 'Нархи қониқтирмади'), (5, 'Ўлчов олиш учун борилади'), (6, 'Сотилди')], default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
        ),
    ]
