# Generated by Django 5.2.4 on 2025-08-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
        ('client', '0002_alter_client_options_alter_client_fio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Заяавка', 'verbose_name_plural': 'Заяавки'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Мижоз'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='solution',
            field=models.IntegerField(choices=[(-1, 'Сотув амалга ошмади'), (0, 'Керак эмас'), (1, 'Қайта телефон қилиш'), (2, 'Телеграм орқали маълумот берилди'), (3, 'Локация юборилади'), (4, 'Нархи қониқтирмади'), (5, 'Ўлчов олиш учун борилади'), (6, 'Сотилди')], default=None, null=True, verbose_name='Код ответа'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменение'),
        ),
    ]
