# Generated by Django 5.2.4 on 2025-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0002_alter_invoice_options_alter_invoice_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='solution',
            field=models.IntegerField(choices=[(-1, 'Сотув амалга ошмади'), (0, 'Керак эмас'), (1, 'Қайта телефон қилиш'), (2, 'Телеграмда маълумот берилди'), (3, 'Локация юборилади'), (4, 'Нархи қониқтирмади'), (5, 'Замерга борилади'), (6, 'Сотилди')], default=None, null=True, verbose_name='Код ответа'),
        ),
    ]
