# Generated by Django 5.2.4 on 2026-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0003_alter_invoice_desc_alter_invoice_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='solution',
            field=models.IntegerField(choices=[(-1, 'Сотув амалга ошмади'), (0, 'Керак эмас'), (1, 'Қайта телефон қилиш'), (2, 'Телеграмда маълумот берилди'), (3, 'Мижоздан локация олиш'), (4, 'Нархи қониқтирмади'), (5, 'Замерга борилади'), (6, 'Сотилди')], default=None, null=True, verbose_name='Код ответа'),
        ),
    ]
