# Generated by Django 5.2.4 on 2025-08-18 10:04

import django.db.models.deletion
import djmoney.models.fields
import filer.fields.folder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_design_price_currency_and_more'),
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='historicaldesign',
            name='folder',
        ),
        migrations.AlterField(
            model_name='design',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldesign',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldesign',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.design')),
                ('folder', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_files', to='filer.folder')),
            ],
        ),
    ]
