# Generated by Django 5.2.4 on 2025-08-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_remove_design_folder_remove_historicaldesign_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtype',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
