# Generated by Django 5.2.4 on 2025-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_alter_design_metering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='price',
        ),
        migrations.RemoveField(
            model_name='design',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='historicaldesign',
            name='price',
        ),
        migrations.RemoveField(
            model_name='historicaldesign',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='design',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldesign',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
