# Generated by Django 5.2.4 on 2025-11-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_remove_design_price_remove_design_price_currency_and_more'),
        ('metering', '0009_alter_historicalmetering_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='design',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='design',
            name='metering',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metering.metering', verbose_name='Замер'),
        ),
        migrations.AlterField(
            model_name='designtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='designtype',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.design', verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='designtype',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicaldesign',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='historicaldesign',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='historicaldesign',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='historicaldesign',
            name='metering',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering.metering', verbose_name='Замер'),
        ),
    ]
