# Generated by Django 5.2.4 on 2025-07-31 17:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region='UZ', serialize=False)),
                ('fio', models.CharField(max_length=255)),
            ],
        ),
    ]
