# Generated by Django 5.2.4 on 2025-08-05 10:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Мижоз', 'verbose_name_plural': 'Мижозлар'},
        ),
        migrations.AlterField(
            model_name='client',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region='UZ', serialize=False, verbose_name='Номер телефона'),
        ),
    ]
