# Generated by Django 5.2.4 on 2026-04-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0004_alter_historicalrover_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrover',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ровер', 'verbose_name_plural': 'historical Роверы'},
        ),
        migrations.AlterModelOptions(
            name='rover',
            options={'verbose_name': 'Ровер', 'verbose_name_plural': 'Роверы'},
        ),
    ]
