# Generated by Django 5.2.4 on 2025-07-31 11:44

import django.db.models.deletion
import filer.fields.folder
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('folder_images', filer.fields.folder.FilerFolderField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.folder')),
            ],
        ),
    ]
