# Generated by Django 5.2.4 on 2025-08-01 09:53

import django.db.models.deletion
import filer.fields.folder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('order', '0002_remove_order_created_date_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('detailing', 'Деталировка'), ('working', 'Заказ на сырье'), ('assembly', 'Сборка'), ('installing', 'Установка'), ('done', 'Готов')], default='created', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='folder_documents',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_document', to='filer.folder'),
        ),
        migrations.AlterField(
            model_name='order',
            name='folder_images',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_image', to='filer.folder'),
        ),
        migrations.AlterField(
            model_name='order',
            name='folder_schemas',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_schema', to='filer.folder'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('detailing', 'Деталировка'), ('working', 'Заказ на сырье'), ('assembly', 'Сборка'), ('installing', 'Установка'), ('done', 'Готов')], default='created', max_length=255),
        ),
    ]
