# Generated by Django 5.2.4 on 2025-08-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_historicalorder_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('change_status_order', 'Order change status'), ('reverse_status_order', 'Order reverse status')]},
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('detailing', 'Деталировка'), ('working', 'Заказ на сырье'), ('assembly', 'Сборка'), ('installing', 'Установка'), ('done', 'Готов')], default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('detailing', 'Деталировка'), ('working', 'Заказ на сырье'), ('assembly', 'Сборка'), ('installing', 'Установка'), ('done', 'Готов')], default='created', max_length=32),
        ),
    ]
