# Generated by Django 5.2.4 on 2025-08-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options_alter_client_fio_and_more'),
        ('order', '0004_alter_order_options_alter_historicalorder_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Заказ', 'verbose_name_plural': 'historical Заказы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('change_status_order', 'Order change status'), ('reverse_status_order', 'Order reverse status')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='address_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на яндекс карты'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='advance',
            field=models.FloatField(verbose_name='Аванс'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client', verbose_name='Мижоз'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='currency',
            field=models.CharField(choices=[('$', 'Доллар($)'), ('sum', 'Сўм')], default='$', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='end_date',
            field=models.DateField(verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='reception_date',
            field=models.DateField(verbose_name='Дата получение'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('detailing', 'Деталировка'), ('working', 'Заказ на сырье'), ('assembly', 'Сборка'), ('installing', 'Установка'), ('done', 'Готов')], default='created', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на яндекс карты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='advance',
            field=models.FloatField(verbose_name='Аванс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Мижоз'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('$', 'Доллар($)'), ('sum', 'Сўм')], default='$', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reception_date',
            field=models.DateField(verbose_name='Дата получение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('detailing', 'Деталировка'), ('working', 'Заказ на сырье'), ('assembly', 'Сборка'), ('installing', 'Установка'), ('done', 'Готов')], default='created', max_length=32, verbose_name='Статус'),
        ),
    ]
