# Generated by Django 5.2.4 on 2025-08-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_historicalorder_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
