# Generated by Django 5.2.4 on 2025-08-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0003_metering_invoice_alter_metering_address'),
        ('order', '0006_remove_historicalorder_name_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='metering',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering.metering'),
        ),
        migrations.AddField(
            model_name='order',
            name='metering',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metering.metering'),
        ),
    ]
