# Generated by Django 5.2.4 on 2025-08-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_historicalorder_metering_order_metering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('change_status_order', 'Order change status'), ('reverse_status_order', 'Order reverse status'), ('view_order_price', 'Order price view')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
