# Generated by Django 5.2.4 on 2025-08-15 13:00

import django.db.models.deletion
import djmoney.models.fields
import filer.fields.folder
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('order', '0008_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='folder_documents',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='folder_images',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='folder_schemas',
        ),
        migrations.RemoveField(
            model_name='order',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='folder_documents',
        ),
        migrations.RemoveField(
            model_name='order',
            name='folder_images',
        ),
        migrations.RemoveField(
            model_name='order',
            name='folder_schemas',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='design_folder',
            field=filer.fields.folder.FilerFolderField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='filer.folder'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='lost_money',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='lost_money_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistani Som')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistani Som')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='design_folder',
            field=filer.fields.folder.FilerFolderField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_design_folder', to='filer.folder'),
        ),
        migrations.AddField(
            model_name='order',
            name='lost_money',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lost_money_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistani Som')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistani Som')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True),
        ),
    ]
