# Generated by Django 5.2.4 on 2025-08-18 10:04

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_historicalorder_lost_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='lost_money',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='lost_money_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lost_money',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lost_money_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
