# Generated by Django 5.2.4 on 2025-08-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_designtype_name'),
        ('order', '0011_alter_historicalorder_lost_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='design_folder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='design_folder',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='design_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='design.designtype'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='design.designtype'),
        ),
    ]
