# Generated by Django 5.2.4 on 2025-08-19 13:54

import django.db.models.deletion
import filer.fields.folder
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('order', '0012_remove_historicalorder_design_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='folder',
            field=filer.fields.folder.FilerFolderField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='filer.folder'),
        ),
        migrations.AddField(
            model_name='order',
            name='folder',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_folder', to='filer.folder'),
        ),
    ]
