# Generated by Django 5.2.4 on 2025-08-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_historicalorder_folder_order_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
    ]
