# Generated by Django 5.2.4 on 2025-08-19 16:11

import django.db.models.deletion
import djmoney.models.fields
import filer.fields.folder
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options_alter_client_fio_and_more'),
        ('design', '0004_designtype_name'),
        ('filer', '0017_image__transparent'),
        ('metering', '0006_alter_historicalmetering_status_and_more'),
        ('order', '0014_delete_historicalorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True)),
                ('lost_money_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True)),
                ('lost_money', djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('detailing', 'Деталировка'), ('working', 'Заказ на сырье'), ('assembly', 'Сборка'), ('installing', 'Установка'), ('done', 'Готов')], default='created', max_length=32, verbose_name='Статус')),
                ('reception_date', models.DateField(verbose_name='Дата получение')),
                ('end_date', models.DateField(verbose_name='Дата сдачи')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на яндекс карты')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client', verbose_name='Мижоз')),
                ('design_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='design.designtype')),
                ('folder', filer.fields.folder.FilerFolderField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='filer.folder')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metering', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering.metering')),
            ],
            options={
                'verbose_name': 'historical Заказ',
                'verbose_name_plural': 'historical Заказы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
