# Generated by Django 5.2.4 on 2025-08-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_historicalorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='lost_money',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='price',
        ),
    ]
