# Generated by Django 5.2.4 on 2025-09-29 09:23

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_remove_design_price_remove_design_price_currency_and_more'),
        ('metering', '0008_alter_historicalmetering_status_and_more'),
        ('order', '0016_remove_historicalorder_lost_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='design_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='design.designtype', verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='metering',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering.metering', verbose_name='Замеры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='design_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='design.designtype', verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lost_money',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True, verbose_name='Полученная сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='metering',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metering.metering', verbose_name='Замеры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, null=True, verbose_name='Все сумма'),
        ),
    ]
