# Generated by Django 5.2.4 on 2026-02-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_created_at'),
        ('design', '0007_alter_design_confirm_alter_design_created_at_and_more'),
        ('metering', '0011_alter_metering_client'),
        ('order', '0017_alter_historicalorder_design_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Мижоз'),
        ),
        migrations.AlterField(
            model_name='order',
            name='design_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design.designtype', verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='metering',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.metering', verbose_name='Замеры'),
        ),
    ]
