# Generated by Django 5.2.4 on 2026-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_client_alter_order_design_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Скидка'),
        ),
    ]
