# Generated by Django 5.2.4 on 2026-07-11 16:12
# Pre-existing model/DB drift found while working on Item 2 (order.models.Order.id/price
# field definitions were already ahead of the migration history before this change) —
# split out from the Item 2 migration below so it isn't attributed to that work.

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0019_historicalorder_discount_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="id",
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=0, max_digits=12, null=True, verbose_name="Вся сумма"
            ),
        ),
    ]
