# Generated by Django 5.2.4 on 2026-07-11 16:12
# Item 2: count_days becomes a required stored field, end_date becomes nullable,
# a new WAITING status is added, status gets db_index=True, and the new editable
# order_number field is added (decision b) and backfilled from id.
# Also folds in the 'Мижоз' -> 'Клиент' verbose_name fix (Item 0).

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_number_and_count_days(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    for order in Order.objects.all().iterator():
        update_fields = []
        if not order.order_number:
            order.order_number = order.id
            update_fields.append("order_number")
        if order.end_date and order.reception_date:
            days = (order.end_date - order.reception_date).days - 1
            order.count_days = max(days, 1)
            update_fields.append("count_days")
        if update_fields:
            order.save(update_fields=update_fields)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_client_created_at"),
        ("order", "0020_alter_historicalorder_id_alter_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="count_days",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество дней"),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="order_number",
            field=models.PositiveIntegerField(
                db_index=True, null=True, verbose_name="Номер заказа"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="count_days",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество дней"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(
                db_index=True, null=True, unique=True, verbose_name="Номер заказа"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="client.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата сдачи"),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидание"),
                    ("created", "Создан"),
                    ("detailing", "Деталировка"),
                    ("working", "Заказ на сырье"),
                    ("assembly", "Сборка"),
                    ("installing", "Установка"),
                    ("done", "Готов"),
                ],
                db_index=True,
                default="created",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата сдачи"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидание"),
                    ("created", "Создан"),
                    ("detailing", "Деталировка"),
                    ("working", "Заказ на сырье"),
                    ("assembly", "Сборка"),
                    ("installing", "Установка"),
                    ("done", "Готов"),
                ],
                db_index=True,
                default="created",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.RunPython(backfill_order_number_and_count_days, noop),
    ]
