# Generated by Django 5.2.4 on 2026-07-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0021_order_count_days_order_order_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorder",
            name="count_days",
        ),
        migrations.RemoveField(
            model_name="order",
            name="count_days",
        ),
    ]
