# Generated by Django 5.2.4 on 2025-08-05 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_options_alter_client_fio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('dont_need', 'Керак эмас'), ('re_phone', 'Қайта телефон қилиш'), ('price_problem', 'Нархи қониқтирмади'), ('sold_out', 'Сотилди')], default='created', max_length=255)),
                ('address', models.TextField()),
                ('address_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
        ),
    ]
