# Generated by Django 5.2.4 on 2025-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metering',
            options={'permissions': [('change_status', 'Metring change status')], 'verbose_name': 'Замер', 'verbose_name_plural': 'Замери'},
        ),
        migrations.AddField(
            model_name='metering',
            name='currency',
            field=models.CharField(choices=[('$', 'Доллар($)'), ('sum', 'Сўм')], default='$', max_length=255),
        ),
        migrations.AddField(
            model_name='metering',
            name='price',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
