# Generated by Django 5.2.4 on 2025-08-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0002_alter_invoice_options_alter_invoice_client_and_more'),
        ('metering', '0002_alter_metering_options_metering_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metering',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='call_center.invoice'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
