# Generated by Django 5.2.4 on 2025-08-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0003_alter_invoice_desc_alter_invoice_solution'),
        ('client', '0002_alter_client_options_alter_client_fio_and_more'),
        ('metering', '0003_metering_invoice_alter_metering_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metering',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='address_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Адрес ссылка'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Мижоз'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='currency',
            field=models.CharField(choices=[('$', 'Доллар($)'), ('sum', 'Сўм')], default='$', max_length=255, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='call_center.invoice', verbose_name='Call-center инвойс'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='price',
            field=models.FloatField(editable=False, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('dont_need', 'Керак эмас'), ('re_phone', 'Қайта телефон қилиш'), ('price_problem', 'Нархи қониқтирмади'), ('sold_out', 'Сотилди')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
