# Generated by Django 5.2.4 on 2025-08-15 12:59

import django.db.models.deletion
import filer.fields.folder
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0003_alter_invoice_desc_alter_invoice_solution'),
        ('client', '0002_alter_client_options_alter_client_fio_and_more'),
        ('filer', '0017_image__transparent'),
        ('metering', '0004_alter_metering_address_alter_metering_address_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metering',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='metering',
            name='price',
        ),
        migrations.AddField(
            model_name='metering',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='metering',
            name='folder',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metering_folder', to='filer.folder'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='status',
            field=models.CharField(choices=[('created', 'Заявка олинди'), ('dont_need', 'Отмен болди'), ('re_phone', 'Бошқа кунга ўзгартирилди'), ('done', 'Бажарилди')], default='created', max_length=255, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='HistoricalMetering',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Заявка олинди'), ('dont_need', 'Отмен болди'), ('re_phone', 'Бошқа кунга ўзгартирилди'), ('done', 'Бажарилди')], default='created', max_length=255, verbose_name='Статус')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('address_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Адрес ссылка')),
                ('create_date', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создание')),
                ('date_time', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client', verbose_name='Мижоз')),
                ('folder', filer.fields.folder.FilerFolderField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='filer.folder')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='call_center.invoice', verbose_name='Call-center инвойс')),
            ],
            options={
                'verbose_name': 'historical Замер',
                'verbose_name_plural': 'historical Замери',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
