# Generated by Django 5.2.4 on 2025-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0005_remove_metering_currency_remove_metering_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetering',
            name='status',
            field=models.CharField(choices=[('created', 'Заявка олинди'), ('dont_need', 'Отмен болди'), ('other_day', 'Бошқа кунга ўзгартирилди'), ('done', 'Бажарилди'), ('sold_out', 'Сотилди')], default='created', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='status',
            field=models.CharField(choices=[('created', 'Заявка олинди'), ('dont_need', 'Отмен болди'), ('other_day', 'Бошқа кунга ўзгартирилди'), ('done', 'Бажарилди'), ('sold_out', 'Сотилди')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
