# Generated by Django 5.2.4 on 2025-08-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0006_alter_historicalmetering_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetering',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metering',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
