# Generated by Django 5.2.4 on 2025-09-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0007_historicalmetering_desc_metering_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetering',
            name='status',
            field=models.CharField(choices=[('created', 'Заявка олинди'), ('dont_need', 'Отмен болди'), ('other_day', 'Бошқа кунга ўзгартирилди'), ('metering_done', 'Замерга борилди'), ('done', 'Бажарилди'), ('sold_out', 'Сотилди')], default='created', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='status',
            field=models.CharField(choices=[('created', 'Заявка олинди'), ('dont_need', 'Отмен болди'), ('other_day', 'Бошқа кунга ўзгартирилди'), ('metering_done', 'Замерга борилди'), ('done', 'Бажарилди'), ('sold_out', 'Сотилди')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
