# Generated by Django 5.2.4 on 2025-11-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0008_alter_historicalmetering_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetering',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='historicalmetering',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
