# Generated by Django 5.2.4 on 2026-01-25 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0003_alter_invoice_desc_alter_invoice_solution'),
        ('metering', '0009_alter_historicalmetering_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metering',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='call_center.invoice', verbose_name='Call-center инвойс'),
        ),
    ]
