# Generated by Django 5.2.4 on 2026-02-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_created_at'),
        ('metering', '0010_alter_metering_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metering',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Мижоз'),
        ),
    ]
