# Generated by Django 5.2.4 on 2025-08-15 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('order', '0009_remove_historicalorder_advance_and_more'),
        ('painter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPointer',
            new_name='HistoricalPainter',
        ),
        migrations.RenameModel(
            old_name='Pointer',
            new_name='Painter',
        ),
        migrations.AlterModelOptions(
            name='historicalpainter',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical painter', 'verbose_name_plural': 'historical painters'},
        ),
    ]
