# Generated by Django 5.2.4 on 2025-11-25 16:49

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_historicalorder_design_type_and_more'),
        ('painter', '0004_alter_historicalpainter_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpainter',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalpainter',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='historicalpainter',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='historicalpainter',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='historicalpainter',
            name='square',
            field=models.FloatField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='painter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='painter',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='painter',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='painter',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='painter',
            name='square',
            field=models.FloatField(verbose_name='Площадь'),
        ),
    ]
