# Generated by Django 5.2.4 on 2026-04-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0006_paintertype_historicalpainter_type_painter_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpainter',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Моляр', 'verbose_name_plural': 'historical Моляры'},
        ),
        migrations.AlterModelOptions(
            name='painter',
            options={'verbose_name': 'Моляр', 'verbose_name_plural': 'Моляры'},
        ),
    ]
