# Generated by Django 5.2.4 on 2025-09-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_user_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('user_call_center', 'Call center'), ('user_metering', 'Metering'), ('user_design', 'Design'), ('user_detailing', 'Detailing'), ('user_rover', 'Rover'), ('user_painter', 'Painter'), ('user_assembly', 'Assembly')]},
        ),
    ]
