# Generated by Django 5.2.4 on 2026-03-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('user_call_center', 'Call center'), ('user_metering', 'Metering'), ('user_design', 'Design'), ('user_detailing', 'Detailing'), ('user_rover', 'Rover'), ('user_painter', 'Painter'), ('user_assembly', 'Assembly'), ('user_detailing_manager', 'Detailing manager')]},
        ),
    ]
