# Generated by Django 5.2.4 on 2025-08-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0003_alter_detailing_painter_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailing',
            name='painter_price',
        ),
        migrations.RemoveField(
            model_name='detailing',
            name='painter_price_currency',
        ),
        migrations.RemoveField(
            model_name='detailing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='detailing',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='detailing',
            name='rover_price',
        ),
        migrations.RemoveField(
            model_name='detailing',
            name='rover_price_currency',
        ),
        migrations.RemoveField(
            model_name='historicaldetailing',
            name='painter_price',
        ),
        migrations.RemoveField(
            model_name='historicaldetailing',
            name='painter_price_currency',
        ),
        migrations.RemoveField(
            model_name='historicaldetailing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='historicaldetailing',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='historicaldetailing',
            name='rover_price',
        ),
        migrations.RemoveField(
            model_name='historicaldetailing',
            name='rover_price_currency',
        ),
        migrations.AlterField(
            model_name='detailing',
            name='square',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='square',
            field=models.FloatField(default=0),
        ),
    ]
