# Generated by Django 5.2.4 on 2025-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0004_remove_detailing_painter_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailing',
            name='working_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldetailing',
            name='working_done',
            field=models.BooleanField(default=False),
        ),
    ]
