# Generated by Django 5.2.4 on 2025-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0005_detailing_working_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailing',
            name='painter_square',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detailing',
            name='rover_square',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='painter_square',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='rover_square',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
