# Generated by Django 5.2.4 on 2025-11-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0006_alter_detailing_painter_square_and_more'),
        ('order', '0017_alter_historicalorder_design_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='detailing',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено деталировка'),
        ),
        migrations.AlterField(
            model_name='detailing',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='detailing',
            name='painter_square',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь покраски'),
        ),
        migrations.AlterField(
            model_name='detailing',
            name='rover_square',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь роверов'),
        ),
        migrations.AlterField(
            model_name='detailing',
            name='square',
            field=models.FloatField(default=0, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='detailing',
            name='working_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено заказ на сырье'),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено деталировка'),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='painter_square',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь покраски'),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='rover_square',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь роверов'),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='square',
            field=models.FloatField(default=0, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='historicaldetailing',
            name='working_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено заказ на сырье'),
        ),
    ]
