# Generated by Django 5.2.4 on 2026-03-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0007_alter_detailing_created_at_alter_detailing_done_and_more'),
        ('painter', '0006_paintertype_historicalpainter_type_painter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailing',
            name='pointer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='painter.paintertype', verbose_name='Тип указателей'),
        ),
        migrations.AddField(
            model_name='historicaldetailing',
            name='pointer_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='painter.paintertype', verbose_name='Тип указателей'),
        ),
    ]
