# Generated by Django 5.2.4 on 2026-04-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0008_detailing_pointer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailing',
            name='pointer_type',
        ),
        migrations.RemoveField(
            model_name='historicaldetailing',
            name='pointer_type',
        ),
    ]
