# Generated by Django 5.2.4 on 2025-08-18 10:04

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_historicalprice_price_currency_price_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
