# Generated by Django 5.2.4 on 2025-08-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0007_historicalmetering_desc_metering_desc'),
        ('price', '0003_alter_historicalprice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='metering',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metering.metering'),
        ),
    ]
