# Generated by Django 5.2.4 on 2025-09-05 12:21

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_inventory_inventorytype_calculate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryincalculate',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryincalculate',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
