# Generated by Django 5.2.4 on 2025-09-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_objecttype_inventorytype_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='price.objecttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcalculate',
            name='obj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='price.objecttype'),
        ),
    ]
