# Generated by Django 5.2.4 on 2025-09-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_calculate_obj_historicalcalculate_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcalculate',
            name='count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inventorytype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Кв. / Пог м.'), (2, 'Кол-во')], default=2),
        ),
    ]
