# Generated by Django 5.2.4 on 2025-11-25 16:49

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0009_alter_historicalmetering_date_time_and_more'),
        ('price', '0009_calculate_count_historicalcalculate_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Нарх чикариш', 'verbose_name_plural': 'historical Нарх чикариш'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Нарх чикариш', 'verbose_name_plural': 'Нарх чикариш'},
        ),
        migrations.AlterField(
            model_name='calculate',
            name='amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='count',
            field=models.FloatField(null=True, verbose_name='Кв. м. / Пог м.'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='price.objecttype', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.price', verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='historicalcalculate',
            name='amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='historicalcalculate',
            name='count',
            field=models.FloatField(null=True, verbose_name='Кв. м. / Пог м.'),
        ),
        migrations.AlterField(
            model_name='historicalcalculate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalcalculate',
            name='obj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='price.objecttype', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='historicalcalculate',
            name='price',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='price.price', verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='price.inventorytype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='metering',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering.metering', verbose_name='Замер'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.inventorytype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='inventoryincalculate',
            name='calculate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.calculate', verbose_name='Калькуляция'),
        ),
        migrations.AlterField(
            model_name='inventoryincalculate',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='inventoryincalculate',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='price.inventory', verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='inventoryincalculate',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='inventorytype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='inventorytype',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price.objecttype', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='inventorytype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Кв. / Пог м.'), (2, 'Кол-во')], default=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='price',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='price',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='price',
            name='metering',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metering.metering', verbose_name='Замер'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Нарх'),
        ),
    ]
