# Generated by Django 5.2.4 on 2026-01-25 13:20

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0010_alter_historicalprice_options_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Сумма (Итого)'),
        ),
        migrations.AlterField(
            model_name='historicalcalculate',
            name='amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Сумма (Итого)'),
        ),
    ]
