# Generated by Django 5.2.4 on 2026-02-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0011_alter_calculate_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytype',
            options={'ordering': ['ordering'], 'verbose_name': 'Тип инвентаря', 'verbose_name_plural': 'Типы инвентаря'},
        ),
        migrations.AddField(
            model_name='inventorytype',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='inventoryincalculate',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.inventory', verbose_name='Инвентарь'),
        ),
    ]
