# Generated by Django 5.2.4 on 2026-02-23 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0012_alter_inventorytype_options_inventorytype_ordering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryincalculate',
            name='count',
            field=models.FloatField(default=1, verbose_name='Кол-во'),
        ),
    ]
