# Generated by Django 5.2.4 on 2026-07-11 16:11
# Pre-existing model/DB drift found while working on unrelated Item 0/4/5 fixes
# (metering.price.models.ObjectType.count_name and the Calculate.obj/Price.metering
# field definitions were already ahead of the migration history before this change) —
# split out from the Russian-sweep migration below so it isn't attributed to that work.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering", "0011_alter_metering_client"),
        ("price", "0013_objecttype_count_name_alter_calculate_obj_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttype",
            name="count_name",
            field=models.CharField(
                choices=[("kv", "Кв. м."), ("pog", "Пог. м.")],
                default="kv",
                max_length=255,
                verbose_name="Кол-во тип",
            ),
        ),
        migrations.AlterField(
            model_name="calculate",
            name="obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="price.objecttype",
                verbose_name="Объект",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="metering",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metering.metering",
                verbose_name="Замер",
            ),
        ),
    ]
