# Generated by Django 5.2.4 on 2026-07-11 16:11
# Russian i18n sweep (Item 0): 'Нарх чикариш' -> 'Расчёт цены', 'Нарх' -> 'Цена'.

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0014_objecttype_count_name_alter_calculate_obj_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalprice",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Расчёт цены",
                "verbose_name_plural": "historical Расчёт цены",
            },
        ),
        migrations.AlterModelOptions(
            name="price",
            options={"verbose_name": "Расчёт цены", "verbose_name_plural": "Расчёт цены"},
        ),
        migrations.AlterField(
            model_name="calculate",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="price.price", verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalculate",
            name="price",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="price.price",
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinventory",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="historicalprice",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryincalculate",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Цена"
            ),
        ),
    ]
